version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "8899:8899"
    environment:
      PRISMA_CONFIG: |
        port: 8899
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: briefgenius
            password: briefgenius
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: briefgenius
      POSTGRES_PASSWORD: briefgenius
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: